# Generated by Django 6.0.2 on 2026-02-10 22:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "scan_status",
                    models.CharField(
                        blank=True,
                        help_text="Result of scanning the path for a video file (e.g. OK, No movie file found, More than 1 video file found: ...).",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        help_text="File system path to the media file or folder.",
                        max_length=500,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True,
                        help_text="Release or publication year.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the record was added to the database.",
                    ),
                ),
                (
                    "acquired_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the item was physically added to the collection (bought, downloaded, etc.).",
                        null=True,
                    ),
                ),
                (
                    "consumed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the item was watched or read.",
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("book", "Book"), ("comic", "Comic")],
                        help_text="Kind of publication: book or comic.",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "pages",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of pages.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "db_table": "books",
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "scan_status",
                    models.CharField(
                        blank=True,
                        help_text="Result of scanning the path for a video file (e.g. OK, No movie file found, More than 1 video file found: ...).",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        help_text="File system path to the media file or folder.",
                        max_length=500,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True,
                        help_text="Release or publication year.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the record was added to the database.",
                    ),
                ),
                (
                    "acquired_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the item was physically added to the collection (bought, downloaded, etc.).",
                        null=True,
                    ),
                ),
                (
                    "consumed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the item was watched or read.",
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("movie", "Movie"), ("documentary", "Documentary")],
                        help_text="Kind of film: movie or documentary.",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("director", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "length",
                    models.IntegerField(
                        blank=True,
                        help_text="Duration in minutes",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "frames",
                    models.IntegerField(
                        blank=True,
                        help_text="Total number of frames",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
                "db_table": "movies",
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "scan_status",
                    models.CharField(
                        blank=True,
                        help_text="Result of scanning the path for a video file (e.g. OK, No movie file found, More than 1 video file found: ...).",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        help_text="File system path to the media file or folder.",
                        max_length=500,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True,
                        help_text="Release or publication year.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the record was added to the database.",
                    ),
                ),
                (
                    "acquired_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the item was physically added to the collection (bought, downloaded, etc.).",
                        null=True,
                    ),
                ),
                (
                    "consumed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the item was watched or read.",
                        null=True,
                    ),
                ),
                (
                    "seasons",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of seasons",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "episodes",
                    models.IntegerField(
                        blank=True,
                        help_text="Total number of episodes",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        help_text="Showrunner or creator of the series.",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Series",
                "verbose_name_plural": "Series",
                "db_table": "series",
            },
        ),
        migrations.CreateModel(
            name="MovieColorPalette",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="Short unique id (MD5 hex truncated to 6 chars).",
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this palette is used for display (e.g. one active per movie).",
                    ),
                ),
                (
                    "calculation_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the color analysis was run.",
                    ),
                ),
                (
                    "calculation_duration_seconds",
                    models.FloatField(
                        blank=True,
                        help_text="Duration of calculation in seconds",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_black_and_white",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the analysis detected a predominantly black-and-white movie.",
                    ),
                ),
                (
                    "colors",
                    models.TextField(
                        help_text='JSON array of hex color strings (e.g. ["#4c4650", ...]).'
                    ),
                ),
                (
                    "clusters_nb",
                    models.IntegerField(
                        help_text="Number of color clusters",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "frame_skip",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of frames to skip during analysis",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "resize_width",
                    models.IntegerField(
                        blank=True,
                        help_text="Width for resizing frames",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "resize_height",
                    models.IntegerField(
                        blank=True,
                        help_text="Height for resizing frames",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "batch_size",
                    models.IntegerField(
                        blank=True,
                        help_text="Batch size for processing",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "clustering_method",
                    models.CharField(
                        blank=True,
                        help_text="Algorithm used for color clustering (e.g. kmeans, cv2).",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "saturation_factor",
                    models.CharField(
                        blank=True,
                        help_text="Saturation factor applied during analysis (stored as string).",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "saturation_threshold",
                    models.IntegerField(
                        blank=True,
                        help_text="Saturation threshold value used during analysis.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "runtime",
                    models.CharField(
                        blank=True,
                        help_text="Execution environment for the analysis (e.g. GPU, CPU).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        db_column="movie_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_palettes",
                        to="cinematheque_app.movie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movie Color Palette",
                "verbose_name_plural": "Movie Color Palettes",
                "db_table": "movie_color_palettes",
                "ordering": ["-calculation_date"],
            },
        ),
    ]
