# Generated by Django 6.0.2 on 2026-02-10 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinematheque_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="poster",
            field=models.URLField(
                blank=True,
                help_text="URL of the poster or cover image.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="rating",
            field=models.IntegerField(
                blank=True,
                help_text="Personal rating from 1 to 5.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="recommendation_source",
            field=models.CharField(
                blank=True,
                help_text="Where this item was recommended from (e.g. friend, review site).",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="poster",
            field=models.URLField(
                blank=True,
                help_text="URL of the poster or cover image.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="rating",
            field=models.IntegerField(
                blank=True,
                help_text="Personal rating from 1 to 5.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="recommendation_source",
            field=models.CharField(
                blank=True,
                help_text="Where this item was recommended from (e.g. friend, review site).",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="series",
            name="poster",
            field=models.URLField(
                blank=True,
                help_text="URL of the poster or cover image.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="rating",
            field=models.IntegerField(
                blank=True,
                help_text="Personal rating from 1 to 5.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="recommendation_source",
            field=models.CharField(
                blank=True,
                help_text="Where this item was recommended from (e.g. friend, review site).",
                max_length=500,
                null=True,
            ),
        ),
    ]
