# Generated by Django 6.0.3 on 2026-04-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinematheque_app", "0002_add_recommendation_poster_rating_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
